receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:5317

exporters:
  debug:
    verbosity: detailed

processors:
    batch:

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
    extensions: [zpages]
    pipelines:
        metrics:
            receivers: [otlp]
            # processors: [batch]
            exporters: [debug]
